version: '3'
services:
  mongo-sakan:
    image: mongo:4
    container_name: mongo-sakan
    ports:
      - '27017:27017'
    volumes:
      - ./src/database/scripts:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    networks:
      - sakan
    command: --replSet rs1
networks:
  sakan:
volumes:
  mongo_data:
